name: Deploy to GitHub Pages

on:
  push:
    branches: 'master'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        uses: AutoModality/action-clean@v1
        
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Installing Bun
        uses: oven-sh/setup-bun@v1
        with:
            bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: build
        env:
          BASE_PATH: '/ImageWebcamToAsciiRenderer'
        run: |
          bun run build
          touch dist/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'dist/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1